<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:foo="http://foo.com" exclude-result-prefixes="foo">
	<xsl:output method="html" encoding="UTF-8" indent="yes"/>

	<xsl:template match="Documentations">
		<html>
			<head>
				<xsl:call-template name="GetHeadData"/>
				<title>
					<xsl:value-of select="./Name"/>
				</title>
			</head>
			<body>
				<div id="top">
					<!-- do not remove this div, it is closed by doxygen! -->
					<div id="titlearea">
						<table cellspacing="0" cellpadding="0">
							<tbody>
								<tr id="projectrow">
									<td id="projectalign">
										<div id="projectname">Xml2Dox<span id="projectnumber">&#160;1.0.0 Alpha</span>
										</div>
										<div id="projectbrief">Xml2Dox is an application that allows to create a documentation like the documentations generate by the application doxygen for your XSLT/XML file thanks to specifics comments.</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<!-- end header part -->
					<!-- Generated by Doxygen 1.9.3 -->
					<script type="text/javascript" src="menudata.js"/>
					<script type="text/javascript" src="menu.js"/>
					<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */
					</script>
					<div id="main-nav"/>
					<div id="nav-path" class="navpath">
						<ul>
							<li class="navelem">
								<a class="el" href="namespace_xml2_dox.html">Xml2Dox</a>
							</li>
							<li class="navelem">
								<a class="el" href="namespace_xml2_dox_1_1_librairie.html">Librairie</a>
							</li>
							<li class="navelem">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html">XslDocToXml</a>
							</li>
						</ul>
					</div>
				</div>
				<!-- top -->
				<div class="header">
					<div class="summary">
						<a href="#pub-methods">Global Variables</a>
						<a href="#pri-methods">Templates</a>
						<a href="#pri-attribs">Private Attributes</a>
					</div>
					<div class="headertitle">
						<div class="title">
							<xsl:value-of select="./Name"/>
						</div>
					</div>
				</div>
				<!--header-->
				<div class="contents">

					<p>Classe permettant de lancer de processus de création d'une documentation des feuilles xslt dans un format xml propriétaire  
						<a href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#details">More...</a>
					</p>
					<table class="memberdecls">
						<tr class="heading">
							<td colspan="2">
								<h2 class="groupheader">
									<a id="pub-methods" name="pub-methods"/>
Public Member Functions</h2>
							</td>
						</tr>
						<tr class="memitem:a89282b4d4f7fbb775d4f0bc8c7a226fd">
							<td class="memItemLeft" align="right" valign="top">&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#a89282b4d4f7fbb775d4f0bc8c7a226fd">XslDocToXml</a> (<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xslt_doc_options.html">XsltDocOptions</a> options)</td>
						</tr>
						<tr class="separator:a89282b4d4f7fbb775d4f0bc8c7a226fd">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
						<tr class="memitem:ad78c5ee30160b761b15b7f97b0a64c49">
							<td class="memItemLeft" align="right" valign="top">bool&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#ad78c5ee30160b761b15b7f97b0a64c49">GenerateXml</a> ()</td>
						</tr>
						<tr class="separator:ad78c5ee30160b761b15b7f97b0a64c49">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
					</table>
					<table class="memberdecls">
						<tr class="heading">
							<td colspan="2">
								<h2 class="groupheader">
									<a id="pri-methods" name="pri-methods"/>
Private Member Functions</h2>
							</td>
						</tr>
						<tr class="memitem:a14cb89aa9052e50412ffd53c26aa3c3a">
							<td class="memItemLeft" align="right" valign="top">void&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#a14cb89aa9052e50412ffd53c26aa3c3a">TreatNode</a> (ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a> result, XComment comment, XElement element)</td>
						</tr>
						<tr class="separator:a14cb89aa9052e50412ffd53c26aa3c3a">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
						<tr class="memitem:ace62845dfe1d0b93909535a68e8de23d">
							<td class="memItemLeft" align="right" valign="top">void&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#ace62845dfe1d0b93909535a68e8de23d">TreatOuptutComment</a> (ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a> result, XComment comment)</td>
						</tr>
						<tr class="separator:ace62845dfe1d0b93909535a68e8de23d">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
						<tr class="memitem:ab92f9d4fddf35d43a798deb9e2149972">
							<td class="memItemLeft" align="right" valign="top">void&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#ab92f9d4fddf35d43a798deb9e2149972">TreatTemplateComment</a> (ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a> result, XComment comment, XElement element)</td>
						</tr>
						<tr class="separator:ab92f9d4fddf35d43a798deb9e2149972">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
					</table>
					<table class="memberdecls">
						<tr class="heading">
							<td colspan="2">
								<h2 class="groupheader">
									<a id="pri-attribs" name="pri-attribs"/>
Private Attributes</h2>
							</td>
						</tr>
						<tr class="memitem:a09de6cdc64f00def46381f72e0e1e860">
							<td class="memItemLeft" align="right" valign="top">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xslt_doc_options.html">XsltDocOptions</a>&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#a09de6cdc64f00def46381f72e0e1e860">Options</a>
							</td>
						</tr>
						<tr class="memdesc:a09de6cdc64f00def46381f72e0e1e860">
							<td class="mdescLeft">&#160;</td>
							<td class="mdescRight">Les options pour la génération de la documentation  <a href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#a09de6cdc64f00def46381f72e0e1e860">More...</a>
								<br />
							</td>
						</tr>
						<tr class="separator:a09de6cdc64f00def46381f72e0e1e860">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
						<tr class="memitem:a7bb9b26577766f3bdeb3097fd4e4b32c">
							<td class="memItemLeft" align="right" valign="top">List&lt; string &gt;&#160;</td>
							<td class="memItemRight" valign="bottom">
								<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xsl_doc_to_xml.html#a7bb9b26577766f3bdeb3097fd4e4b32c">ouputComment</a>
							</td>
						</tr>
						<tr class="separator:a7bb9b26577766f3bdeb3097fd4e4b32c">
							<td class="memSeparator" colspan="2">&#160;</td>
						</tr>
					</table>
					<a name="details" id="details"/>
					<h2 class="groupheader">Detailed Description</h2>
					<div class="textblock">
						<p >Classe permettant de lancer de processus de création d'une documentation des feuilles xslt dans un format xml propriétaire </p>
					</div>
					<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
					<a id="a89282b4d4f7fbb775d4f0bc8c7a226fd" name="a89282b4d4f7fbb775d4f0bc8c7a226fd"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#a89282b4d4f7fbb775d4f0bc8c7a226fd">&#9670;&nbsp;</a>
						</span>XslDocToXml()</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">Xml2Dox.Librairie.XslDocToXml.XslDocToXml </td>
												<td>(</td>
												<td class="paramtype">
													<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xslt_doc_options.html">XsltDocOptions</a>&#160;</td>
												<td class="paramname">
													<em>options</em>
												</td>
												<td>)</td>
												<td/>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">inline</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

						</div>
					</div>
					<h2 class="groupheader">Member Function Documentation</h2>
					<a id="ad78c5ee30160b761b15b7f97b0a64c49" name="ad78c5ee30160b761b15b7f97b0a64c49"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#ad78c5ee30160b761b15b7f97b0a64c49">&#9670;&nbsp;</a>
						</span>GenerateXml()</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">bool Xml2Dox.Librairie.XslDocToXml.GenerateXml </td>
												<td>(</td>
												<td class="paramname"/>
												<td>)</td>
												<td/>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">inline</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

						</div>
					</div>
					<a id="a14cb89aa9052e50412ffd53c26aa3c3a" name="a14cb89aa9052e50412ffd53c26aa3c3a"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#a14cb89aa9052e50412ffd53c26aa3c3a">&#9670;&nbsp;</a>
						</span>TreatNode()</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">void Xml2Dox.Librairie.XslDocToXml.TreatNode </td>
												<td>(</td>
												<td class="paramtype">ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a>&#160;</td>
												<td class="paramname">
													<em>result</em>, </td>
											</tr>
											<tr>
												<td class="paramkey"/>
												<td/>
												<td class="paramtype">XComment&#160;</td>
												<td class="paramname">
													<em>comment</em>, </td>
											</tr>
											<tr>
												<td class="paramkey"/>
												<td/>
												<td class="paramtype">XElement&#160;</td>
												<td class="paramname">
													<em>element</em>&#160;</td>
											</tr>
											<tr>
												<td/>
												<td>)</td>
												<td/>
												<td/>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">inline</span>
											<span class="mlabel">private</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

						</div>
					</div>
					<a id="ace62845dfe1d0b93909535a68e8de23d" name="ace62845dfe1d0b93909535a68e8de23d"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#ace62845dfe1d0b93909535a68e8de23d">&#9670;&nbsp;</a>
						</span>TreatOuptutComment()</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">void Xml2Dox.Librairie.XslDocToXml.TreatOuptutComment </td>
												<td>(</td>
												<td class="paramtype">ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a>&#160;</td>
												<td class="paramname">
													<em>result</em>, </td>
											</tr>
											<tr>
												<td class="paramkey"/>
												<td/>
												<td class="paramtype">XComment&#160;</td>
												<td class="paramname">
													<em>comment</em>&#160;</td>
											</tr>
											<tr>
												<td/>
												<td>)</td>
												<td/>
												<td/>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">inline</span>
											<span class="mlabel">private</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

						</div>
					</div>
					<a id="ab92f9d4fddf35d43a798deb9e2149972" name="ab92f9d4fddf35d43a798deb9e2149972"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#ab92f9d4fddf35d43a798deb9e2149972">&#9670;&nbsp;</a>
						</span>TreatTemplateComment()</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">void Xml2Dox.Librairie.XslDocToXml.TreatTemplateComment </td>
												<td>(</td>
												<td class="paramtype">ref <a class="el" href="class_xml2_dox_1_1_librairie_1_1_documentations.html">Documentations</a>&#160;</td>
												<td class="paramname">
													<em>result</em>, </td>
											</tr>
											<tr>
												<td class="paramkey"/>
												<td/>
												<td class="paramtype">XComment&#160;</td>
												<td class="paramname">
													<em>comment</em>, </td>
											</tr>
											<tr>
												<td class="paramkey"/>
												<td/>
												<td class="paramtype">XElement&#160;</td>
												<td class="paramname">
													<em>element</em>&#160;</td>
											</tr>
											<tr>
												<td/>
												<td>)</td>
												<td/>
												<td/>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">inline</span>
											<span class="mlabel">private</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

						</div>
					</div>
					<h2 class="groupheader">Member Data Documentation</h2>
					<a id="a09de6cdc64f00def46381f72e0e1e860" name="a09de6cdc64f00def46381f72e0e1e860"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#a09de6cdc64f00def46381f72e0e1e860">&#9670;&nbsp;</a>
						</span>Options</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">
													<a class="el" href="class_xml2_dox_1_1_librairie_1_1_xslt_doc_options.html">XsltDocOptions</a> Xml2Dox.Librairie.XslDocToXml.Options</td>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">private</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
						<div class="memdoc">

							<p>Les options pour la génération de la documentation </p>

						</div>
					</div>
					<a id="a7bb9b26577766f3bdeb3097fd4e4b32c" name="a7bb9b26577766f3bdeb3097fd4e4b32c"/>
					<h2 class="memtitle">
						<span class="permalink">
							<a href="#a7bb9b26577766f3bdeb3097fd4e4b32c">&#9670;&nbsp;</a>
						</span>ouputComment</h2>

					<div class="memitem">
						<div class="memproto">
							<table class="mlabels">
								<tr>
									<td class="mlabels-left">
										<table class="memname">
											<tr>
												<td class="memname">List&lt;string&gt; Xml2Dox.Librairie.XslDocToXml.ouputComment</td>
											</tr>
										</table>
									</td>
									<td class="mlabels-right">
										<span class="mlabels">
											<span class="mlabel">private</span>
										</span>
									</td>
								</tr>
							</table>
						</div>
					</div>
					<hr/>The documentation for this class was generated from the following file:<ul>
						<li>Xml2Dox - Librairie/Xml/<a class="el" href="_xsl_doc_to_xml_8cs.html">XslDocToXml.cs</a>
						</li>
					</ul>
				</div>
				<!-- contents -->
				<!-- start footer part -->
				<hr class="footer"/>
				<address class="footer">
					<small>
Generated by&#160;<a href="https://www.doxygen.org/index.html">
							<img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/>
						</a> 1.9.3
					</small>
				</address>
			</body>
		</html>

	</xsl:template>

	<xsl:template name="GetHeadData">
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=11"/>
		<meta name="generator" content="Xml2Dox 1.0.0"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"/>
		<script type="text/javascript" src="dynsections.js"/>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
	</xsl:template>
</xsl:stylesheet>