<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:foo="http://foo.com" exclude-result-prefixes="foo">
	<xsl:output method="html" encoding="UTF-8" indent="yes"/>

	<xsl:variable name="WhiteSpace" select="'&#160;'"/>

	<xsl:template match="Documentations"> 
		<html>
			<head>
				<xsl:call-template name="GetHeadData"/>
				<title>
					<xsl:value-of select="./Name"/>
				</title>
			</head>
			<body>
				<div class="header">
					<div class="summary">
						<a href="#pub-methods">Global Variables | </a>
						<a href="#pri-methods">Templates</a>
					</div>
					<div class="headertitle">
						<div class="title">
							<xsl:value-of select="./Name"/>
						</div>
					</div>
				</div>
				<div class="contents">
					<p>
						<xsl:value-of select="substring(./Description, 1, 150)"/>
						<a href="#details">More...</a>
					</p>
					<table class="memberdecls">
						<tr class="heading">
							<td colspan="2">
								<h2 class="groupheader">Global Variables</h2>
							</td>
						</tr>
						<xsl:call-template name="ListGlobalVariable"/>
					</table>
					<table class="memberdecls">
						<tr class="heading">
							<td colspan="2">
								<h2 class="groupheader">Templates</h2>
							</td>
						</tr>
						<xsl:call-template name="ListTemplate"/>
					</table>
					<xsl:call-template name="GetDetailedDescription"/>

					<h2 class="groupheader">Global Variables Documentation</h2>
					<xsl:call-template name="GetDetailedVariable"/>

					<h2 class="groupheader">Templates Documentation</h2>
					<xsl:call-template name="GetDetailedTemplate"/>

					<hr/>The documentation for this XSL file was generated from the following file:<ul>
						<li>Xml2Dox - Librairie/Xml/<a class="el" href="_xsl_doc_to_xml_8cs.html">XslDocToXml.cs</a>
						</li>
					</ul>
				</div>
				<hr class="footer"/>
				<address class="footer">
					<small>
					Generated by&#160;<a href="https://www.doxygen.org/index.html">
							<img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/>
						</a> 1.9.3
					</small>
				</address>
			</body>
		</html>
	</xsl:template>

	<xsl:template name="GetDetailedVariable">
		<xsl:for-each select="./Variables/Variable">
			<!--<a id="ace62845dfe1d0b93909535a68e8de23d" name="ace62845dfe1d0b93909535a68e8de23d"/>-->
			<h2 class="memtitle">
				<!--<span class="permalink">
					<a href="#ace62845dfe1d0b93909535a68e8de23d">&#9670;</a>
				</span>-->
				<xsl:value-of select="./@Name"/>
			</h2>
			<div class="memitem">
				<div class="memproto">
					<table class="mlabels">
						<tr>
							<td class="mlabels-left">
								<table class="memname">
									<tr>
										<td class="memname">
											<xsl:value-of select="concat('??? ', ./@Name, ' =&gt; ', ./@Value)"/>
										</td>
									</tr>
								</table>
							</td>
							<td class="mlabels-right">
								<!--<span class="mlabels">
									<span class="mlabel">inline</span>
									<span class="mlabel">private</span>
								</span>-->
							</td>
						</tr>
					</table>
				</div>
				<div class="memdoc">
					<xsl:call-template name="GetDescRemarks"/>
				</div>
			</div>
		</xsl:for-each>
	</xsl:template>

	<xsl:template name="GetDetailedTemplate">
		<xsl:for-each select="./Templates/Template">
			<!--<a id="ace62845dfe1d0b93909535a68e8de23d" name="ace62845dfe1d0b93909535a68e8de23d"/>-->
			<h2 class="memtitle">
				<!--<span class="permalink">
					<a href="#ace62845dfe1d0b93909535a68e8de23d">&#9670;</a>
				</span>-->
				<xsl:value-of select="concat(@Name, '()')"/>
			</h2>
			<div class="memitem">
				<div class="memproto">
					<table class="mlabels">
						<tr>
							<td class="mlabels-left">
								<table class="memname">
									<tr>
										<td class="memname">
											<xsl:value-of select="concat('??? ', ./@Name, '(')"/>
											<xsl:for-each select="./Params/Param">
												<xsl:value-of select="@Code"/>
												<xsl:if test="position() != last()">
													<xsl:value-of select="', '"/>
												</xsl:if>
											</xsl:for-each>
											<xsl:value-of select="')'"/>
										</td>
									</tr>
								</table>
							</td>
							<td class="mlabels-right">
								<!--<span class="mlabels">
									<span class="mlabel">inline</span>
									<span class="mlabel">private</span>
								</span>-->
							</td>
						</tr>
					</table>
				</div>
				<div class="memdoc">
					<xsl:call-template name="GetDescRemarks"/>
					<xsl:if test="./Params != ''">
						<dl class="params">
							<dt>Parameters</dt>
							<dd>
								<table class="params">
									<tbody>
										<xsl:for-each select="./Params/Param">
											<tr>
												<td class="paramname">
													<xsl:value-of select="./@Code"/>
												</td>
												<td>
													<xsl:value-of select="./@Description"/>
												</td>
											</tr>
										</xsl:for-each>
									</tbody>
								</table>
							</dd>
						</dl>
					</xsl:if>
				</div>
			</div>
		</xsl:for-each>
	</xsl:template>

	<xsl:template name="GetDescRemarks">
		<xsl:if test="./Description !=''">
			<p>
				<xsl:value-of select="./Description"/>
			</p>
		</xsl:if>
		<xsl:if test="./Remarks != ''">
			<p>
				<xsl:value-of select="./Remarks"/>
			</p>
		</xsl:if>
	</xsl:template>

	<xsl:template name="ListGlobalVariable">
		<xsl:for-each select="./Variables/Variable">
			<tr class="memitem:a89282b4d4f7fbb775d4f0bc8c7a226fd">
				<td class="memItemLeft" align="right" valign="top">???</td>
				<td class="memItemRight" valign="bottom">
					<xsl:element name="a">
						<xsl:attribute name="href">
							<xsl:value-of select="concat('#', ./@Name)"/>
						</xsl:attribute>
						<xsl:attribute name="class">
							<xsl:value-of select="'el'"/>
						</xsl:attribute>
						<xsl:value-of select="./@Name"/>
					</xsl:element>					
					<xsl:if test="./Description != ''">
						<br/>
						<xsl:value-of select="./Description"/>
					</xsl:if>
				</td>
			</tr>
			<tr class="separator:a89282b4d4f7fbb775d4f0bc8c7a226fd">
				<td class="memSeparator" colspan="2">&#160;</td>
			</tr>
		</xsl:for-each>
	</xsl:template>

	<xsl:template name="ListTemplate">
		<xsl:for-each select="./Templates/Template">
			<tr class="memitem:a14cb89aa9052e50412ffd53c26aa3c3a">
				<td class="memItemLeft" align="right" valign="top">???</td>
				<td class="memItemRight" valign="bottom">
					<xsl:element name="a">
						<xsl:attribute name="href">
							<xsl:value-of select="concat('#', ./@Name)"/>
						</xsl:attribute>
						<xsl:attribute name="class">
							<xsl:value-of select="'el'"/>
						</xsl:attribute>
						<xsl:value-of select="./@Name"/>
					</xsl:element>
					<xsl:value-of select="'('"/>
					<xsl:for-each select="./Params/Param">
						<xsl:value-of select="@Code"/>
						<xsl:if test="position() != last()">
							<xsl:value-of select="','"/>
						</xsl:if>
					</xsl:for-each>
					<xsl:value-of select="')'"/>
					<xsl:if test="./Description != ''">
						<br/>
						<xsl:value-of select="./Description"/>
					</xsl:if>
				</td>
			</tr>
			<tr class="separator:a14cb89aa9052e50412ffd53c26aa3c3a">
				<td class="memSeparator" colspan="2">&#160;</td>
			</tr>
		</xsl:for-each>
	</xsl:template>

	<xsl:template name="GetDetailedDescription">
		<a name="details" id="details"/>
		<h2 class="groupheader">Detailed Description</h2>
		<div class="textblock">
			<xsl:if test="./@Version != ''">
				<p>
					<xsl:value-of select="concat('Version : ', ./@Version)"/>
				</p>
			</xsl:if>
			<xsl:if test="./Description != ''">
				<p>
					<xsl:value-of select="./Description"/>
				</p>
			</xsl:if>
			<xsl:if test="./Authors != ''">
				<p>Authors :</p>
				<ul>
					<xsl:for-each select="./Authors/Author">
						<li>
							<xsl:value-of select="text()"/>
						</li>
					</xsl:for-each>
				</ul>
			</xsl:if>
		</div>
	</xsl:template>

	<xsl:template name="GetHeadData">
		<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=11"/>
		<meta name="generator" content="Xml2Dox 1.0.0"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link href="tabs.css" rel="stylesheet" type="text/css"/>
		<script type="text/javascript" src="jquery.js"/>
		<script type="text/javascript" src="dynsections.js"/>
		<link href="doxygen.css" rel="stylesheet" type="text/css" />
	</xsl:template>
</xsl:stylesheet>